In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

Now I want to create my model. I will join the previous files.

In [2]:
# merging the csv files
tournaments = pd.concat(
    map(pd.read_csv, ['tourneyResults2003.csv','tourneyResults2004.csv','tourneyResults2005.csv','tourneyResults2006.csv','tourneyResults2007.csv','tourneyResults2008.csv','tourneyResults2009.csv','tourneyResults2010.csv','tourneyResults2011.csv', 'tourneyResults2012.csv', 'tourneyResults2013.csv', 'tourneyResults2014.csv', 'tourneyResults2015.csv', 'tourneyResults2016.csv','tourneyResults2017.csv','tourneyResults2018.csv','tourneyResults2019.csv','tourneyResults2021.csv']), ignore_index=True)
tournaments

,Unnamed: 0,team_1,Seed_1,team_0,Seed_0,winner,team_score_mean_1,num_ot_mean_1,fgm_mean_1,fga_mean_1,...,or_median_0,dr_median_0,ast_median_0,to_median_0,stl_median_0,blk_median_0,pf_median_0,Last14days_0,last14days_wins_0,season
0,0,1411,16,1421,16,0,72.800000,0.033333,24.733333,55.266667,...,12.0,22.0,13.0,16.0,7.0,3.0,19.0,3,3,2003
1,1,1400,1,1421,16,1,78.857143,0.035714,28.000000,62.428571,...,12.0,22.0,13.0,16.0,7.0,3.0,19.0,3,3,2003
2,2,1112,1,1436,16,1,85.214286,0.071429,30.321429,65.714286,...,12.0,26.0,13.0,14.0,6.0,3.0,16.0,3,3,2003
3,3,1112,1,1211,9,1,85.214286,0.071429,30.321429,65.714286,...,12.0,26.0,17.0,15.0,6.0,3.0,18.0,2,1,2003
4,4,1153,8,1211,9,0,67.321429,0.000000,22.892857,56.678571,...,12.0,26.0,17.0,15.0,6.0,3.0,18.0,2,1,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1176,61,1325,13,1438,4,1,71.662093,0.106346,24.881647,55.830189,...,10.0,24.0,13.0,11.0,6.0,3.0,17.0,69,39,2021
1177,62,1222,2,1333,12,1,72.282272,0.072289,25.376936,59.111876,...,10.0,22.0,13.0,13.0,6.0,3.0,18.0,61,24,2021
1178,63,1329,4,1333,12,0,73.073950,0.078992,25.292437,56.095798,...,10.0,22.0,13.0,13.0,6.0,3.0,18.0,61,24,2021
1179,64,1260,8,1333,12,0,66.688380,0.068662,23.841549,53.170775,...,10.0,22.0,13.0,13.0,6.0,3.0,18.0,61,24,2021
1180,65,1234,2,1332,7,0,71.772575,0.061873,24.961538,55.877926,...,11.0,24.0,14.0,13.0,7.0,3.0,18.0,77,53,2021

In [3]:
tournaments = pd.DataFrame(tournaments)
tournaments

,Unnamed: 0,team_1,Seed_1,team_0,Seed_0,winner,team_score_mean_1,num_ot_mean_1,fgm_mean_1,fga_mean_1,...,or_median_0,dr_median_0,ast_median_0,to_median_0,stl_median_0,blk_median_0,pf_median_0,Last14days_0,last14days_wins_0,season
0,0,1411,16,1421,16,0,72.800000,0.033333,24.733333,55.266667,...,12.0,22.0,13.0,16.0,7.0,3.0,19.0,3,3,2003
1,1,1400,1,1421,16,1,78.857143,0.035714,28.000000,62.428571,...,12.0,22.0,13.0,16.0,7.0,3.0,19.0,3,3,2003
2,2,1112,1,1436,16,1,85.214286,0.071429,30.321429,65.714286,...,12.0,26.0,13.0,14.0,6.0,3.0,16.0,3,3,2003
3,3,1112,1,1211,9,1,85.214286,0.071429,30.321429,65.714286,...,12.0,26.0,17.0,15.0,6.0,3.0,18.0,2,1,2003
4,4,1153,8,1211,9,0,67.321429,0.000000,22.892857,56.678571,...,12.0,26.0,17.0,15.0,6.0,3.0,18.0,2,1,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1176,61,1325,13,1438,4,1,71.662093,0.106346,24.881647,55.830189,...,10.0,24.0,13.0,11.0,6.0,3.0,17.0,69,39,2021
1177,62,1222,2,1333,12,1,72.282272,0.072289,25.376936,59.111876,...,10.0,22.0,13.0,13.0,6.0,3.0,18.0,61,24,2021
1178,63,1329,4,1333,12,0,73.073950,0.078992,25.292437,56.095798,...,10.0,22.0,13.0,13.0,6.0,3.0,18.0,61,24,2021
1179,64,1260,8,1333,12,0,66.688380,0.068662,23.841549,53.170775,...,10.0,22.0,13.0,13.0,6.0,3.0,18.0,61,24,2021
1180,65,1234,2,1332,7,0,71.772575,0.061873,24.961538,55.877926,...,11.0,24.0,14.0,13.0,7.0,3.0,18.0,77,53,2021

In [4]:
tournaments = tournaments.drop(['Unnamed: 0'], axis=1)

In [5]:
tournaments

,team_1,Seed_1,team_0,Seed_0,winner,team_score_mean_1,num_ot_mean_1,fgm_mean_1,fga_mean_1,fgm3_mean_1,...,or_median_0,dr_median_0,ast_median_0,to_median_0,stl_median_0,blk_median_0,pf_median_0,Last14days_0,last14days_wins_0,season
0,1411,16,1421,16,0,72.800000,0.033333,24.733333,55.266667,5.933333,...,12.0,22.0,13.0,16.0,7.0,3.0,19.0,3,3,2003
1,1400,1,1421,16,1,78.857143,0.035714,28.000000,62.428571,5.857143,...,12.0,22.0,13.0,16.0,7.0,3.0,19.0,3,3,2003
2,1112,1,1436,16,1,85.214286,0.071429,30.321429,65.714286,7.035714,...,12.0,26.0,13.0,14.0,6.0,3.0,16.0,3,3,2003
3,1112,1,1211,9,1,85.214286,0.071429,30.321429,65.714286,7.035714,...,12.0,26.0,17.0,15.0,6.0,3.0,18.0,2,1,2003
4,1153,8,1211,9,0,67.321429,0.000000,22.892857,56.678571,6.678571,...,12.0,26.0,17.0,15.0,6.0,3.0,18.0,2,1,2003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1176,1325,13,1438,4,1,71.662093,0.106346,24.881647,55.830189,7.276158,...,10.0,24.0,13.0,11.0,6.0,3.0,17.0,69,39,2021
1177,1222,2,1333,12,1,72.282272,0.072289,25.376936,59.111876,7.648881,...,10.0,22.0,13.0,13.0,6.0,3.0,18.0,61,24,2021
1178,1329,4,1333,12,0,73.073950,0.078992,25.292437,56.095798,6.737815,...,10.0,22.0,13.0,13.0,6.0,3.0,18.0,61,24,2021
1179,1260,8,1333,12,0,66.688380,0.068662,23.841549,53.170775,5.959507,...,10.0,22.0,13.0,13.0,6.0,3.0,18.0,61,24,2021
1180,1234,2,1332,7,0,71.772575,0.061873,24.961538,55.877926,6.767559,...,11.0,24.0,14.0,13.0,7.0,3.0,18.0,77,53,2021

In [6]:
tournaments.isna().any()

team_1               False
Seed_1               False
team_0               False
Seed_0               False
winner               False
                     ...
blk_median_0         False
pf_median_0          False
Last14days_0         False
last14days_wins_0    False
season               False
Length: 70, dtype: bool

In [7]:
tournaments.season.value_counts()

2012    67
2013    67
2019    67
2018    67
2017    67
2016    67
2015    67
2014    67
2011    67
2021    66
2004    64
2010    64
2009    64
2008    64
2007    64
2006    64
2005    64
2003    64
Name: season, dtype: int64

In [8]:
#converting all columns to integers
tournaments = tournaments.astype('float64').round(3)
tournaments.describe()

,team_1,Seed_1,team_0,Seed_0,winner,team_score_mean_1,num_ot_mean_1,fgm_mean_1,fga_mean_1,fgm3_mean_1,...,or_median_0,dr_median_0,ast_median_0,to_median_0,stl_median_0,blk_median_0,pf_median_0,Last14days_0,last14days_wins_0,season
count,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,...,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000
mean,1232.670618,7.068586,1355.459780,6.953429,0.483489,72.810293,0.063505,25.622045,56.404092,6.690159,...,11.522015,23.936494,14.051651,13.207451,6.655800,3.484759,17.758679,33.571550,20.135478,2011.650296
std,84.723643,4.787116,84.185728,4.634656,0.499939,4.399439,0.024951,1.724697,2.740644,0.886510,...,1.349962,1.374476,1.412519,1.277137,1.013608,0.984079,1.371385,20.120341,12.740178,5.274224
min,1101.000000,1.000000,1124.000000,1.000000,0.000000,58.714000,0.000000,19.714000,40.911000,3.870000,...,7.000000,19.000000,10.000000,9.000000,4.000000,1.000000,14.000000,0.000000,0.000000,2003.000000
25%,1163.000000,3.000000,1287.000000,3.000000,0.000000,69.832000,0.049000,24.525000,54.712000,6.082000,...,11.000000,23.000000,13.000000,13.000000,6.000000,3.000000,17.000000,16.000000,10.000000,2007.000000
50%,1231.000000,6.000000,1376.000000,6.000000,0.000000,72.548000,0.063000,25.515000,56.379000,6.555000,...,11.000000,24.000000,14.000000,13.000000,6.500000,3.000000,18.000000,32.000000,18.000000,2012.000000
75%,1280.000000,11.000000,1433.000000,11.000000,1.000000,75.613000,0.077000,26.752000,58.091000,7.333000,...,12.000000,25.000000,15.000000,14.000000,7.000000,4.000000,19.000000,50.000000,29.000000,2016.000000
max,1458.000000,16.000000,1463.000000,16.000000,1.000000,86.386000,0.172000,30.930000,65.714000,9.470000,...,16.000000,29.000000,18.000000,19.000000,12.000000,9.000000,22.000000,91.000000,64.000000,2021.000000

In [9]:
#tournaments.num_ot_mean_1.unique()

In [10]:
dupes = tournaments[tournaments.duplicated()]
dupes

Empty DataFrame
Columns: [team_1, Seed_1, team_0, Seed_0, winner, team_score_mean_1, num_ot_mean_1, fgm_mean_1, fga_mean_1, fgm3_mean_1, fga3_mean_1, ftm_mean_1, fta_mean_1, or_mean_1, dr_mean_1, ast_mean_1, to_mean_1, stl_mean_1, blk_mean_1, pf_mean_1, team_score_median_1, num_ot_median_1, fgm_median_1, fga_median_1, fgm3_median_1, fga3_median_1, ftm_median_1, fta_median_1, or_median_1, dr_median_1, ast_median_1, to_median_1, stl_median_1, blk_median_1, pf_median_1, Last14days_1, last14days_wins_1, team_score_mean_0, num_ot_mean_0, fgm_mean_0, fga_mean_0, fgm3_mean_0, fga3_mean_0, ftm_mean_0, fta_mean_0, or_mean_0, dr_mean_0, ast_mean_0, to_mean_0, stl_mean_0, blk_mean_0, pf_mean_0, team_score_median_0, num_ot_median_0, fgm_median_0, fga_median_0, fgm3_median_0, fga3_median_0, ftm_median_0, fta_median_0, or_median_0, dr_median_0, ast_median_0, to_median_0, stl_median_0, blk_median_0, pf_median_0, Last14days_0, last14days_wins_0, season]
Index: []

[0 rows x 70 columns]

Checking to see if there are any duplicates. There aren't.

# Building Model

# Ridge Regression with 15 Features

In [11]:
from sklearn.model_selection import TimeSeriesSplit # will split data properly when we are doing feature selection
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr15 = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)
sfs = SequentialFeatureSelector(rr15, n_features_to_select=15, direction='forward', cv=split) #forward starts with zero features, pick the feature tha timporve model accuracy the most and then keep doing that until we get to 20

In [12]:
removed_columns = ["season", "winner"] #columns that won't run in the model

In [13]:
selected_columns = tournaments.columns[~tournaments.columns.isin(removed_columns)] #columns that we want to include in the model

In [14]:
sfs.fit(tournaments[selected_columns], tournaments['winner'])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=15)

In [15]:
predictors = list(selected_columns[sfs.get_support()])
predictors

['team_1',
 'Seed_1',
 'team_0',
 'Seed_0',
 'team_score_mean_1',
 'num_ot_mean_1',
 'dr_mean_1',
 'stl_mean_1',
 'blk_mean_1',
 'num_ot_median_1',
 'fga_median_1',
 'pf_median_1',
 'dr_mean_0',
 'num_ot_median_0',
 'dr_median_0']

In [16]:
def backtest(data, model, predictors, start=2, step=1):
    all_predictions = [] # list odf dataframe, each dataframe is the prediction for a single seasons
    seasons  = sorted(tournaments["season"].unique()) #list of seasons tha texist in data
    
    for i in range(start, len(seasons), step): #we progress with step parameter (one season at a time)
        season = seasons[i] # pull out the season number / 2003 will be the first season
        
        train = tournaments[tournaments["season"] < season] #for 2005, training will be 2004 and 2003
        test = tournaments[tournaments['season'] == season] #test will be 2005 (or whatever the current season is)
        
        model.fit(train[predictors], train['winner']) #this will take training data, all the predictors
        preds = model.predict(test[predictors]) #generate predictions from the test set we want 
        
        #by default model.fit  will return numpy array, but we want to convert it to a pandas series, keep index the same as test set index to make it easier to combin actuals and predictions
        preds = pd.Series(preds, index=test.index)
        
        combined = pd.concat([test['winner'], preds], axis=1) #axis=1 means treats target and preds as two columns, axis=0 would return one column and everything would be returned in rows
        combined.columns = ['actual', 'predictions'] #renaming columns
        
        all_predictions.append(combined) #this will be a list of five dataframes, one for each season, then we will combine all 
        
    return pd.concat(all_predictions)

In [17]:
predictions = backtest(tournaments, rr15, predictors)

In [18]:
predictions

      actual  predictions
128      0.0          1.0
129      1.0          1.0
130      1.0          1.0
131      1.0          1.0
132      0.0          1.0
...      ...          ...
1176     1.0          0.0
1177     1.0          1.0
1178     0.0          1.0
1179     0.0          1.0
1180     0.0          1.0

[1053 rows x 2 columns]

In [19]:
from sklearn.metrics import accuracy_score
accuracy_score(predictions['actual'],predictions['predictions'])

0.698005698005698

In [20]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(predictions['actual'],predictions['predictions']))

              precision    recall  f1-score   support

         0.0       0.71      0.71      0.71       546
         1.0       0.69      0.68      0.68       507

    accuracy                           0.70      1053
   macro avg       0.70      0.70      0.70      1053
weighted avg       0.70      0.70      0.70      1053

## Manual Implementation of Measurement Metrics

To get a more granular look at the performance of the models used in this prediciton, I am calculating precision, recall and accuracy for each model to see how the model handles the data better.

In [21]:
predsDF = pd.merge(tournaments, predictions, left_index=True, right_index=True)
predsDF

,team_1,Seed_1,team_0,Seed_0,winner,team_score_mean_1,num_ot_mean_1,fgm_mean_1,fga_mean_1,fgm3_mean_1,...,ast_median_0,to_median_0,stl_median_0,blk_median_0,pf_median_0,Last14days_0,last14days_wins_0,season,actual,predictions
128,1105.0,16.0,1324.0,16.0,0.0,70.155,0.071,23.869,59.429,6.595,...,14.0,13.0,7.0,3.0,19.0,6.0,4.0,2005.0,0.0,1.0
129,1314.0,1.0,1324.0,16.0,1.0,80.824,0.077,28.385,61.396,7.363,...,14.0,13.0,7.0,3.0,19.0,6.0,4.0,2005.0,1.0,1.0
130,1112.0,3.0,1429.0,14.0,1.0,83.922,0.044,30.267,64.067,7.078,...,15.0,12.5,5.0,2.0,14.0,10.0,9.0,2005.0,1.0,1.0
131,1112.0,3.0,1412.0,11.0,1.0,83.922,0.044,30.267,64.067,7.078,...,16.5,14.0,12.0,3.0,20.0,14.0,9.0,2005.0,1.0,1.0
132,1261.0,6.0,1412.0,11.0,0.0,71.841,0.057,25.227,54.148,6.466,...,16.5,14.0,12.0,3.0,20.0,14.0,9.0,2005.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1176,1325.0,13.0,1438.0,4.0,1.0,71.662,0.106,24.882,55.830,7.276,...,13.0,11.0,6.0,3.0,17.0,69.0,39.0,2021.0,1.0,0.0
1177,1222.0,2.0,1333.0,12.0,1.0,72.282,0.072,25.377,59.112,7.649,...,13.0,13.0,6.0,3.0,18.0,61.0,24.0,2021.0,1.0,1.0
1178,1329.0,4.0,1333.0,12.0,0.0,73.074,0.079,25.292,56.096,6.738,...,13.0,13.0,6.0,3.0,18.0,61.0,24.0,2021.0,0.0,1.0
1179,1260.0,8.0,1333.0,12.0,0.0,66.688,0.069,23.842,53.171,5.960,...,13.0,13.0,6.0,3.0,18.0,61.0,24.0,2021.0,0.0,1.0
1180,1234.0,2.0,1332.0,7.0,0.0,71.773,0.062,24.962,55.878,6.768,...,14.0,13.0,7.0,3.0,18.0,77.0,53.0,2021.0,0.0,1.0

In [22]:
# getting TP, TN, FP and FN value counts for the data
predsDF['truepos'] = np.where((predsDF['actual']==1) & (predsDF['predictions']==1),1,0)
predsDF['trueneg']= np.where((predsDF['actual']==0) & (predsDF['predictions']==0),1,0)
predsDF['falsepos']= np.where((predsDF['actual']==0) & (predsDF['predictions']==1),1,0)
predsDF['falseneg']= np.where((predsDF['actual']==1) & (predsDF['predictions']==0),1,0)
predsDF

,team_1,Seed_1,team_0,Seed_0,winner,team_score_mean_1,num_ot_mean_1,fgm_mean_1,fga_mean_1,fgm3_mean_1,...,pf_median_0,Last14days_0,last14days_wins_0,season,actual,predictions,truepos,trueneg,falsepos,falseneg
128,1105.0,16.0,1324.0,16.0,0.0,70.155,0.071,23.869,59.429,6.595,...,19.0,6.0,4.0,2005.0,0.0,1.0,0,0,1,0
129,1314.0,1.0,1324.0,16.0,1.0,80.824,0.077,28.385,61.396,7.363,...,19.0,6.0,4.0,2005.0,1.0,1.0,1,0,0,0
130,1112.0,3.0,1429.0,14.0,1.0,83.922,0.044,30.267,64.067,7.078,...,14.0,10.0,9.0,2005.0,1.0,1.0,1,0,0,0
131,1112.0,3.0,1412.0,11.0,1.0,83.922,0.044,30.267,64.067,7.078,...,20.0,14.0,9.0,2005.0,1.0,1.0,1,0,0,0
132,1261.0,6.0,1412.0,11.0,0.0,71.841,0.057,25.227,54.148,6.466,...,20.0,14.0,9.0,2005.0,0.0,1.0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1176,1325.0,13.0,1438.0,4.0,1.0,71.662,0.106,24.882,55.830,7.276,...,17.0,69.0,39.0,2021.0,1.0,0.0,0,0,0,1
1177,1222.0,2.0,1333.0,12.0,1.0,72.282,0.072,25.377,59.112,7.649,...,18.0,61.0,24.0,2021.0,1.0,1.0,1,0,0,0
1178,1329.0,4.0,1333.0,12.0,0.0,73.074,0.079,25.292,56.096,6.738,...,18.0,61.0,24.0,2021.0,0.0,1.0,0,0,1,0
1179,1260.0,8.0,1333.0,12.0,0.0,66.688,0.069,23.842,53.171,5.960,...,18.0,61.0,24.0,2021.0,0.0,1.0,0,0,1,0
1180,1234.0,2.0,1332.0,7.0,0.0,71.773,0.062,24.962,55.878,6.768,...,18.0,77.0,53.0,2021.0,0.0,1.0,0,0,1,0

In [23]:
predsDF2 = predsDF.groupby(['season']).sum()
predsDF2.columns
predsDF3 = predsDF2[['team_1', 'team_0','actual', 'predictions', 'truepos',
       'trueneg', 'falsepos', 'falseneg']]
predsDF3
predsDF3['precision'] = predsDF3['truepos']/(predsDF3['truepos']+predsDF3['falsepos'])
predsDF3['accuracy'] = (predsDF3['truepos']+predsDF3['trueneg'])/(predsDF3['truepos']+predsDF3['falsepos']+predsDF3['trueneg']+predsDF3['falseneg'])
predsDF3['recall'] = predsDF3['truepos']/(predsDF3['truepos']+predsDF3['falseneg'])
predsDF3 = predsDF3.reset_index()
predsDF3

/var/folders/xb/f5b3swwd2sv23ycj3qfh_45c0000gn/T/ipykernel_90610/840220359.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  predsDF3['precision'] = predsDF3['truepos']/(predsDF3['truepos']+predsDF3['falsepos'])
/var/folders/xb/f5b3swwd2sv23ycj3qfh_45c0000gn/T/ipykernel_90610/840220359.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  predsDF3['accuracy'] = (predsDF3['truepos']+predsDF3['trueneg'])/(predsDF3['truepos']+predsDF3['falsepos']+predsDF3['trueneg']+predsDF3['falseneg'])
/var/folders/xb/f5b3swwd2sv23ycj3qfh_45c0000gn/T/ipykernel_90610/840220359.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  predsDF3['recall'] = predsDF3['truepos']/(predsDF3['truepos']+predsDF3['falseneg'])

,season,team_1,team_0,actual,predictions,truepos,trueneg,falsepos,falseneg,precision,accuracy,recall
0,2005.0,79302.0,87456.0,31.0,42.0,25,16,17,6,0.595238,0.640625,0.806452
1,2006.0,78048.0,86672.0,32.0,29.0,20,23,9,12,0.689655,0.671875,0.625000
2,2007.0,79881.0,87800.0,30.0,28.0,23,29,5,7,0.821429,0.812500,0.766667
3,2008.0,79677.0,88120.0,29.0,25.0,21,31,4,8,0.840000,0.812500,0.724138
4,2009.0,78895.0,86547.0,24.0,29.0,18,29,11,6,0.620690,0.734375,0.750000
5,2010.0,79670.0,86792.0,32.0,33.0,21,20,12,11,0.636364,0.640625,0.656250
6,2011.0,81298.0,90845.0,38.0,26.0,20,23,6,18,0.769231,0.641791,0.526316
7,2012.0,82739.0,89749.0,35.0,32.0,25,25,7,10,0.781250,0.746269,0.714286
8,2013.0,82156.0,88801.0,33.0,31.0,22,25,9,11,0.709677,0.701493,0.666667
9,2014.0,81591.0,90796.0,38.0,25.0,18,22,7,20,0.720000,0.597015,0.473684
10,2015.0,81868.0,91601.0,31.0,34.0,25,27,9,6,0.735294,0.776119,0.806452
11,2016.0,83947.0,92000.0,29.0,27.0,17,28,10,12,0.629630,0.671642,0.586207
12,2017.0,82776.0,91980.0,33.0,46.0,30,18,16,3,0.652174,0.716418,0.909091
13,2018.0,83161.0,90089.0,31.0,29.0,20,27,9,11,0.689655,0.701493,0.645161
14,2019.0,82789.0,90426.0,29.0,26.0,15,27,11,14,0.576923,0.626866,0.517241
15,2021.0,80200.0,88717.0,32.0,39.0,25,20,14,7,0.641026,0.681818,0.781250

I can see that the model has varying performance for the different tournaments but the average performance of the model is:

In [24]:
print("Average accuracy of the model:",predsDF3.accuracy.mean())
print("Average precision of the model:",predsDF3.precision.mean())
print("Average recall of the model:",predsDF3.recall.mean())

Average accuracy of the model: 0.6983389162143827
Average precision of the model: 0.6942646793677998
Average recall of the model: 0.6846787924834713

# Ridge Regression with 10 Features

In [25]:
from sklearn.model_selection import TimeSeriesSplit # will split data properly when we are doing feature selection
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

rr10 = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)
sfs = SequentialFeatureSelector(rr10, n_features_to_select=10, direction='forward', cv=split) #forward starts with zero features, pick the feature tha timporve model accuracy the most and then keep doing that until we get to 20

In [26]:
sfs.fit(tournaments[selected_columns], tournaments['winner'])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=10)

In [27]:
predictors = list(selected_columns[sfs.get_support()])
predictors

['team_1',
 'Seed_1',
 'team_0',
 'Seed_0',
 'team_score_mean_1',
 'stl_mean_1',
 'blk_mean_1',
 'fga_median_1',
 'pf_median_1',
 'dr_median_0']

In [28]:
predictions = backtest(tournaments, rr10, predictors)

In [29]:
predictions

      actual  predictions
128      0.0          1.0
129      1.0          1.0
130      1.0          1.0
131      1.0          1.0
132      0.0          1.0
...      ...          ...
1176     1.0          0.0
1177     1.0          1.0
1178     0.0          1.0
1179     0.0          1.0
1180     0.0          1.0

[1053 rows x 2 columns]

In [30]:
from sklearn.metrics import accuracy_score
accuracy_score(predictions['actual'],predictions['predictions'])

0.6999050332383666

In [31]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(predictions['actual'],predictions['predictions']))

              precision    recall  f1-score   support

         0.0       0.71      0.72      0.71       546
         1.0       0.69      0.68      0.69       507

    accuracy                           0.70      1053
   macro avg       0.70      0.70      0.70      1053
weighted avg       0.70      0.70      0.70      1053

In [32]:
predsDF = pd.merge(tournaments, predictions, left_index=True, right_index=True)
predsDF

# getting TP, TN, FP and FN value counts for the data
predsDF['truepos'] = np.where((predsDF['actual']==1) & (predsDF['predictions']==1),1,0)
predsDF['trueneg']= np.where((predsDF['actual']==0) & (predsDF['predictions']==0),1,0)
predsDF['falsepos']= np.where((predsDF['actual']==0) & (predsDF['predictions']==1),1,0)
predsDF['falseneg']= np.where((predsDF['actual']==1) & (predsDF['predictions']==0),1,0)
predsDF

#calculating precision, accuracy and recall
predsDF2 = predsDF.groupby(['season']).sum()
predsDF2.columns
predsDF3 = predsDF2[['team_1', 'team_0','actual', 'predictions', 'truepos',
       'trueneg', 'falsepos', 'falseneg']]
predsDF3
predsDF3['precision'] = predsDF3['truepos']/(predsDF3['truepos']+predsDF3['falsepos'])
predsDF3['accuracy'] = (predsDF3['truepos']+predsDF3['trueneg'])/(predsDF3['truepos']+predsDF3['falsepos']+predsDF3['trueneg']+predsDF3['falseneg'])
predsDF3['recall'] = predsDF3['truepos']/(predsDF3['truepos']+predsDF3['falseneg'])
predsDF3 = predsDF3.reset_index()
predsDF3

/var/folders/xb/f5b3swwd2sv23ycj3qfh_45c0000gn/T/ipykernel_90610/2209518479.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  predsDF3['precision'] = predsDF3['truepos']/(predsDF3['truepos']+predsDF3['falsepos'])
/var/folders/xb/f5b3swwd2sv23ycj3qfh_45c0000gn/T/ipykernel_90610/2209518479.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  predsDF3['accuracy'] = (predsDF3['truepos']+predsDF3['trueneg'])/(predsDF3['truepos']+predsDF3['falsepos']+predsDF3['trueneg']+predsDF3['falseneg'])
/var/folders/xb/f5b3swwd2sv23ycj3qfh_45c0000gn/T/ipykernel_90610/2209518479.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  predsDF3['recall'] = predsDF3['truepos']/(predsDF3['truepos']+predsDF3['falseneg'])

,season,team_1,team_0,actual,predictions,truepos,trueneg,falsepos,falseneg,precision,accuracy,recall
0,2005.0,79302.0,87456.0,31.0,41.0,25,17,16,6,0.609756,0.656250,0.806452
1,2006.0,78048.0,86672.0,32.0,31.0,21,22,10,11,0.677419,0.671875,0.656250
2,2007.0,79881.0,87800.0,30.0,27.0,23,30,4,7,0.851852,0.828125,0.766667
3,2008.0,79677.0,88120.0,29.0,25.0,21,31,4,8,0.840000,0.812500,0.724138
4,2009.0,78895.0,86547.0,24.0,30.0,18,28,12,6,0.600000,0.718750,0.750000
5,2010.0,79670.0,86792.0,32.0,33.0,21,20,12,11,0.636364,0.640625,0.656250
6,2011.0,81298.0,90845.0,38.0,26.0,20,23,6,18,0.769231,0.641791,0.526316
7,2012.0,82739.0,89749.0,35.0,32.0,25,25,7,10,0.781250,0.746269,0.714286
8,2013.0,82156.0,88801.0,33.0,31.0,22,25,9,11,0.709677,0.701493,0.666667
9,2014.0,81591.0,90796.0,38.0,25.0,18,22,7,20,0.720000,0.597015,0.473684
10,2015.0,81868.0,91601.0,31.0,34.0,25,27,9,6,0.735294,0.776119,0.806452
11,2016.0,83947.0,92000.0,29.0,27.0,17,28,10,12,0.629630,0.671642,0.586207
12,2017.0,82776.0,91980.0,33.0,47.0,31,18,16,2,0.659574,0.731343,0.939394
13,2018.0,83161.0,90089.0,31.0,28.0,19,27,9,12,0.678571,0.686567,0.612903
14,2019.0,82789.0,90426.0,29.0,25.0,15,28,10,14,0.600000,0.641791,0.517241
15,2021.0,80200.0,88717.0,32.0,39.0,25,20,14,7,0.641026,0.681818,0.781250

In [33]:
print("Average accuracy of the model:",predsDF3.accuracy.mean())
print("Average precision of the model:",predsDF3.precision.mean())
print("Average recall of the model:",predsDF3.recall.mean())

Average accuracy of the model: 0.7002483145352782
Average precision of the model: 0.6962277758849779
Average recall of the model: 0.6865097278451526

With only a slight improvement in model accuracy, I will choose to use this model since it is the simpler model (fewer features).

# USING GRID SEARCH - To determine best Alpha values

In [34]:
from numpy import arange
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedKFold
from sklearn.linear_model import LinearRegression


rr = RidgeClassifier()
#model evaluation method
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
#grid definition
grid=dict()
grid['alpha'] = arange(0.01,1,0.01)
# define search
search = GridSearchCV(rr, grid, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)
# perform the search
results = search.fit(tournaments[predictors], tournaments['winner'])
# summarize
print('MAE: %.3f' % results.best_score_)
print('Config: %s' % results.best_params_)

MAE: -0.294
Config: {'alpha': 0.01}

# Ridge Regression with 10 Features and Alpha = 0.01

In [35]:
rr01 = RidgeClassifier(alpha=0.01)

In [36]:
predictions = backtest(tournaments, rr01, predictors)

In [37]:
predictions

      actual  predictions
128      0.0          1.0
129      1.0          1.0
130      1.0          1.0
131      1.0          1.0
132      0.0          1.0
...      ...          ...
1176     1.0          0.0
1177     1.0          1.0
1178     0.0          1.0
1179     0.0          1.0
1180     0.0          1.0

[1053 rows x 2 columns]

In [38]:
from sklearn.metrics import accuracy_score
accuracy_score(predictions['actual'],predictions['predictions'])

0.6999050332383666

In [39]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(predictions['actual'],predictions['predictions']))

              precision    recall  f1-score   support

         0.0       0.71      0.72      0.71       546
         1.0       0.69      0.68      0.69       507

    accuracy                           0.70      1053
   macro avg       0.70      0.70      0.70      1053
weighted avg       0.70      0.70      0.70      1053

In [40]:
predsDF = pd.merge(tournaments, predictions, left_index=True, right_index=True)
predsDF

# getting TP, TN, FP and FN value counts for the data
predsDF['truepos'] = np.where((predsDF['actual']==1) & (predsDF['predictions']==1),1,0)
predsDF['trueneg']= np.where((predsDF['actual']==0) & (predsDF['predictions']==0),1,0)
predsDF['falsepos']= np.where((predsDF['actual']==0) & (predsDF['predictions']==1),1,0)
predsDF['falseneg']= np.where((predsDF['actual']==1) & (predsDF['predictions']==0),1,0)
predsDF

#calculating precision, accuracy and recall
predsDF2 = predsDF.groupby(['season']).sum()
predsDF2.columns
predsDF3 = predsDF2[['team_1', 'team_0','actual', 'predictions', 'truepos',
       'trueneg', 'falsepos', 'falseneg']]
predsDF3
predsDF3['precision'] = predsDF3['truepos']/(predsDF3['truepos']+predsDF3['falsepos'])
predsDF3['accuracy'] = (predsDF3['truepos']+predsDF3['trueneg'])/(predsDF3['truepos']+predsDF3['falsepos']+predsDF3['trueneg']+predsDF3['falseneg'])
predsDF3['recall'] = predsDF3['truepos']/(predsDF3['truepos']+predsDF3['falseneg'])
predsDF3 = predsDF3.reset_index()
predsDF3

/var/folders/xb/f5b3swwd2sv23ycj3qfh_45c0000gn/T/ipykernel_90610/2209518479.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  predsDF3['precision'] = predsDF3['truepos']/(predsDF3['truepos']+predsDF3['falsepos'])
/var/folders/xb/f5b3swwd2sv23ycj3qfh_45c0000gn/T/ipykernel_90610/2209518479.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  predsDF3['accuracy'] = (predsDF3['truepos']+predsDF3['trueneg'])/(predsDF3['truepos']+predsDF3['falsepos']+predsDF3['trueneg']+predsDF3['falseneg'])
/var/folders/xb/f5b3swwd2sv23ycj3qfh_45c0000gn/T/ipykernel_90610/2209518479.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  predsDF3['recall'] = predsDF3['truepos']/(predsDF3['truepos']+predsDF3['falseneg'])

,season,team_1,team_0,actual,predictions,truepos,trueneg,falsepos,falseneg,precision,accuracy,recall
0,2005.0,79302.0,87456.0,31.0,41.0,25,17,16,6,0.609756,0.656250,0.806452
1,2006.0,78048.0,86672.0,32.0,31.0,21,22,10,11,0.677419,0.671875,0.656250
2,2007.0,79881.0,87800.0,30.0,27.0,23,30,4,7,0.851852,0.828125,0.766667
3,2008.0,79677.0,88120.0,29.0,25.0,21,31,4,8,0.840000,0.812500,0.724138
4,2009.0,78895.0,86547.0,24.0,30.0,18,28,12,6,0.600000,0.718750,0.750000
5,2010.0,79670.0,86792.0,32.0,33.0,21,20,12,11,0.636364,0.640625,0.656250
6,2011.0,81298.0,90845.0,38.0,26.0,20,23,6,18,0.769231,0.641791,0.526316
7,2012.0,82739.0,89749.0,35.0,32.0,25,25,7,10,0.781250,0.746269,0.714286
8,2013.0,82156.0,88801.0,33.0,31.0,22,25,9,11,0.709677,0.701493,0.666667
9,2014.0,81591.0,90796.0,38.0,25.0,18,22,7,20,0.720000,0.597015,0.473684
10,2015.0,81868.0,91601.0,31.0,34.0,25,27,9,6,0.735294,0.776119,0.806452
11,2016.0,83947.0,92000.0,29.0,27.0,17,28,10,12,0.629630,0.671642,0.586207
12,2017.0,82776.0,91980.0,33.0,47.0,31,18,16,2,0.659574,0.731343,0.939394
13,2018.0,83161.0,90089.0,31.0,28.0,19,27,9,12,0.678571,0.686567,0.612903
14,2019.0,82789.0,90426.0,29.0,25.0,15,28,10,14,0.600000,0.641791,0.517241
15,2021.0,80200.0,88717.0,32.0,39.0,25,20,14,7,0.641026,0.681818,0.781250

In [41]:
print("Average accuracy of the model:",predsDF3.accuracy.mean())
print("Average precision of the model:",predsDF3.precision.mean())
print("Average recall of the model:",predsDF3.recall.mean())

Average accuracy of the model: 0.7002483145352782
Average precision of the model: 0.6962277758849779
Average recall of the model: 0.6865097278451526

The performance of the ridge regression classifier using Alpha=1 and Alpha=0.01 are identical. The changing of the alpha parameter does not have an effect on the performance of the models. In this case, I could choose either Alpha=0.01 or Alpha = 1.

# Saving Model

In [42]:
import pickle

with open('rr_alpha01','wb') as f:
    pickle.dump(rr01, f)
    
    
#Save the trained model as a pickle string
#rr = pickle.dumps(rr)

In [43]:
import pickle

with open('rr_alpha01', 'rb') as f:
    rr_alpha01 = pickle.load(f)

# RUNNING DATA - 2022 TOURNAMENT

In [44]:
tourneyResults22 = pd.read_csv('tourneyResults2022.csv')
tourneyResults22.dtypes

Unnamed: 0             int64
team_1                 int64
Seed_1                 int64
team_0                 int64
Seed_0                 int64
                      ...
blk_median_0         float64
pf_median_0          float64
Last14days_0           int64
last14days_wins_0      int64
season                 int64
Length: 71, dtype: object

In [45]:
X = tourneyResults22[predictors]
y = tourneyResults22['winner']

In [46]:
predictions = rr_alpha01.predict(X)
predictions

array([0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0.,
       1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1.])

# TESTING ACCURACY OF MODEL

### Ridge Regression

In [47]:
from sklearn.metrics import accuracy_score
accuracy_score(y,predictions)

0.6865671641791045

In [48]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y,predictions))

              precision    recall  f1-score   support

           0       0.71      0.69      0.70        35
           1       0.67      0.69      0.68        32

    accuracy                           0.69        67
   macro avg       0.69      0.69      0.69        67
weighted avg       0.69      0.69      0.69        67